// oregengo-R コードジェネレータ定義データ
char* codegen[] = {
 "/\\/", "\\1\n",
 " \\:", "\\1:\n",
 "\\:", "\\1:\n",
 " jge \\", " rsi-rdi\n jge \\1\n",
 " jlt \\", " rsi-rdi\n jlt \\1\n",
 " jz \\", " rsi-rdi\n jz \\1\n",
 " jnz \\", " rsi-rdi\n jnz \\1\n",
 " jmp \\", " jmp \\1\n",
 " goto\\", " jmp \\1\n",
 " +", " rdi+=rsi\n",
 " -", " exg rdi,rsi\n rdi-=rsi\n",
 " *", " rax=rdi\n mul rsi\n rdi=rax\n",
 " /", " rdx^=rdx\n rax=rsi\n rax&rax\n jge $+9\n rdx--\n div rdi\n rdi=rax\n",
 " neg", " neg rdi\n",
 " not", " not rdi\n",
 " mod", " rdx^=rdx\n rax=rsi\n rax&rax\n jge $+9\n rdx--\n div rdi\n rdi=rdx\n",
 " swap", " exg rdi,rsi\n",
 " push", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n",
 " pop", " rdi=rsi\n rsi=rdx\n rdx=r8\n r8=r9\n r9=r10\n r10=r11\n r11=r12\n",
 " PUSH", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n rax=r15\n (rax)=rdi\n",
 " POP", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n rdi=-8(rax)\n",
 " umul", " rax=rdi\n umul rsi\n rdi=rax\n",
 " udiv", " rdx^=rdx\n rax=rsi\n udiv rdi\n rdi=rax\n",
 " and", " rdi&=rsi\n",
 " or", " rdi|=rsi\n",
 " xor", " rdi^=rsi\n",
 " getchar$,", " call getchar\n",
 " inkey$,", " call inkey\n",
 " \\(rip),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rdi=&\\1(rip)\n",
 " end", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n rax=-8(rax)\n jmp (rax)\n",
 " return", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n r15++\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n rax=-8(rax)\n jmp (rax)\n",
 " jmp@", " jmp (rdi)\n",
 " call@", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n r15=$+15\n (rax)=r15\n jmp (rdi)\n",
 " .data", " align 8\n",
 " ->\\#=", " rcx=\\1\n rcx+=rdi\n rax=rsi\n (rcx)=rax\n",
 " ->\\!=", " rcx=\\1\n rcx+=rdi\n rax=rsi\n (rcx)=eax\n",
 " ->\\%=", " rcx=\\1\n rcx+=rdi\n rax=rsi\n (rcx)=ax\n",
 " ->\\$=", " rcx=\\1\n rcx+=rdi\n rax=rsi\n (rcx)=al\n",
 " ->\\#", " rcx=\\1\n rcx+=rdi\n rax=(rcx)\n rdi=rax\n",
 " ->\\!", " rcx=\\1\n rcx+=rdi\n eax=(rcx)\n ext eax\n rdi=rax\n",
 " ->\\%", " rcx=\\1\n rcx+=rdi\n ax=(rcx)\n ext ax\n rdi=rax\n",
 " ->\\$", " rcx=\\1\n rcx+=rdi\n al=(rcx)\n ext al\n rdi=rax\n",
 " ->@\\(\\)", " r13=\\2\n rcx=\\1\n rcx+=rdi\n rcx=(rcx)\n r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n r15=$+36\n (rax)=r15\n rdi=rsi\n rsi=rdx\n rdx=r8\n r8=r9\n r9=r10\n r10=r11\n r11=r12\n jmp (rcx)\n",
 " ->@\\", " rcx=\\1\n rcx+=rdi\n rcx=(rcx)\n r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n r15=$+36\n (rax)=r15\n rdi=rsi\n rsi=rdx\n rdx=r8\n r8=r9\n r9=r10\n r10=r11\n r11=r12\n jmp (rcx)\n",
 " ->\\", " rcx=\\1\n rdi+=rcx\n",
 " (\\)#(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n eax=(rcx)\n ext eax\n rdi=rax\n",
 " \\!(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n eax=(rcx)\n ext eax\n rdi=rax\n",
 " (\\)%(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n ax=(rcx)\n ext ax\n rdi=rax\n",
 " \\%(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n ax=(rcx)\n ext ax\n rdi=rax\n",
 " (\\)$(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n al=(rcx)\n ext al\n rdi=rax\n",
 " \\$(\\#),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx+=rax\n al=(rcx)\n ext al\n rdi=rax\n",
 " (\\)#(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\#)=", " rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\#)=", " rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " (\\)#(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n eax=(rcx)\n ext eax\n rdi=rax\n",
 " \\!(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n eax=(rcx)\n ext eax\n rdi=rax\n",
 " (\\)%(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n ax=(rcx)\n ext ax\n rdi=rax\n",
 " \\%(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rcx=&\\1\n rcx+=rax\n ax=(rcx)\n ext ax\n rdi=rax\n",
 " (\\)$(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n al=(rcx)\n ext al\n rdi=rax\n",
 " \\$(\\),", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=\\2\n rcx=&\\1\n rcx+=rax\n al=(rcx)\n ext al\n rdi=rax\n",
 " (\\)#(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\)=", " rax=\\2\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\)=", " rax=\\2\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\)=", " rax=\\2\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\)=", " rax=\\2\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\#++", " rcx=&\\1\n rax=(rcx)\n rax++\n (rcx)=rax\n",
 " \\#--", " rcx=&\\1\n rax=(rcx)\n rax--\n (rcx)=rax\n",
 " \\!++", " rcx=&\\1\n eax=(rcx)\n eax++\n (rcx)=eax\n",
 " \\!--", " rcx=&\\1\n eax=(rcx)\n eax--\n (rcx)=eax\n",
 " \\%++", " rcx=&\\1\n ax=(rcx)\n ax++\n (rcx)=ax\n",
 " \\%--", " rcx=&\\1\n ax=(rcx)\n ax--\n (rcx)=ax\n",
 " \\$++", " rcx=&\\1\n al=(rcx)\n al++\n (rcx)=al\n",
 " \\$--", " rcx=&\\1\n al=(rcx)\n al--\n (rcx)=al\n",
 " (\\)#,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n rdi=(rax)\n",
 " \\#,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n rdi=(rax)\n",
 " (\\)!,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n eax=(rax)\n ext eax\n rdi=rax\n",
 " \\!,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n eax=(rax)\n ext eax\n rdi=rax\n",
 " (\\)%,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n ax=(rax)\n ext ax\n rdi=rax\n",
 " \\%,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n ax=(rax)\n ext ax\n rdi=rax\n",
 " (\\)$,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n al=(rax)\n ext al\n rdi=rax\n",
 " \\$,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rax=&\\1\n al=(rax)\n ext al\n rdi=rax\n",
 " \\,", " r12=r11\n r11=r10\n r10=r9\n r9=r8\n r8=rdx\n rdx=rsi\n rsi=rdi\n rdi=\\1\n",
 " (\\)#=", " rax=&\\1\n rax=(rax)\n (rax)=rdi\n",
 " \\#=", " rax=&\\1\n (rax)=rdi\n",
 " (\\)!=", " rax=&\\1\n rax=(rax)\n rcx=rdi\n (rax)=ecx\n",
 " \\!=", " rax=&\\1\n rcx=rdi\n (rax)=ecx\n",
 " (\\)%=", " rax=&\\1\n rax=(rax)\n rcx=rdi\n (rax)=cx\n",
 " \\%=", " rax=&\\1\n rcx=rdi\n (rax)=cx\n",
 " (\\)$=", " rax=&\\1\n rax=(rax)\n rcx=rdi\n (rax)=cl\n",
 " \\$=", " rax=&\\1\n rcx=rdi\n (rax)=cl\n",
 " data\\", " long \\1\n",
 " @\\(\\)", " r13=\\2\n r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n r15=$+28\n (rax)=r15\n rax=\\1\n rax=(rax)\n jmp (rax)\n",
 " @\\", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n r15=$+28\n (rax)=r15\n rax=\\1\n rax=(rax)\n jmp (rax)\n",
 " \\", " r14=1\n rax=__critical\n (rax)=r14\n rax=__stack_p\n r15=(rax)\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n r15--\n (rax)=r15\n r14=0\n rax=__critical\n (rax)=r14\n rax=r15\n r15=$+18\n (rax)=r15\n jmp \\1\n",
NULL
};
