char* codegen[] = {
 "/\\/", "\\1\n",
 " \\:", "\\1:\n",
 "\\:", "\\1:\n",
 " jge \\", " rsi-rdi\n jge \\1\n",
 " jlt \\", " rsi-rdi\n jlt \\1\n",
 " jz \\", " rsi-rdi\n jz \\1\n",
 " jnz \\", " rsi-rdi\n jnz \\1\n",
 " jmp \\", " jmp \\1\n",
 " goto\\", " jmp \\1\n",
 " +", " rdi+=rsi\n",
 " -", " exg rdi,rsi\n rdi-=rsi\n",
 " *", " rax=rdi\n mul rsi\n rdi=rax\n",
 " /", " rdx^=rdx\n rax=rsi\n div rdi\n rdi=rax\n",
 " neg", " neg rdi\n",
 " not", " not rdi\n",
 " mod", " rdx^=rdx\n rax=si\n div rdi\n rdi=rdx\n",
 " swap", " exg rdi,rsi\n",
 " push", " rdx=rsi\n rsi=rdi\n",
 " pop", " rdi=rsi\n rsi=rdx\n",
 " umul", " rax=rdi\n umul rsi\n rdi=rax\n",
 " udiv", " rdx^=rdx\n rax=rsi\n udiv rdi\n rdi=rax\n",
 " and", " rdi&=rsi\n",
 " or", " rdi|=rsi\n",
 " xor", " rdi^=rsi\n",
 " getchar$,", " call getchar\n",
 " inkey$,", " call inkey\n",
 " \\(rip),", " rdx=rsi\n rsi=rdi\n rdi=&\\1(rip)\n",
 " end", " ret\n",
 " return", " ret\n",
 " jmp@", " jmp (rdi)\n",
 " (\\)#(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " \\!(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " (\\)%(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " \\%(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " (\\)$(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " \\$(\\#),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " (\\)#(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\#)=", " rcx=&\\2\n rax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\#)=", " rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\#)=", " rcx=&\\2\n rax=(rcx)\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " (\\)#(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " \\!(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " (\\)%(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " \\%(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " (\\)$(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " \\$(\\!),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n eax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " (\\)#(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\!)=", " rcx=&\\2\n rax^=rax\n eax=(rcx)\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " (\\)#(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " \\!(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " (\\)%(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " \\%(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " (\\)$(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " \\$(\\%),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n ax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " (\\)#(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\%)=", " rcx=&\\2\n rax^=rax\n ax=(rcx)\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " (\\)#(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " \\!(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " (\\)%(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " \\%(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " (\\)$(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " \\$(\\$),", " rdx=rsi\n rsi=rdi\n rcx=&\\2\n rax^=rax\n al=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " (\\)#(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\$)=", " rcx=&\\2\n rax^=rax\n al=(rcx)\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " (\\)#(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rdi=(rcx)\n",
 " \\#(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rdi=(rcx)\n",
 " (\\)!(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " \\!(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n eax=(rcx)\n rdi=rax\n",
 " (\\)%(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " \\%(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax^=rax\n ax=(rcx)\n rdi=rax\n",
 " (\\)$(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " \\$(\\),", " rdx=rsi\n rsi=rdi\n rax=\\2\n rcx=&\\1\n rcx+=rax\n rax^=rax\n al=(rcx)\n rdi=rax\n",
 " (\\)#(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n (rcx)=rdi\n",
 " \\#(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n (rcx)=rdi\n",
 " (\\)!(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " \\!(\\)=", " rax=\\2\n rax+=rax\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=eax\n",
 " (\\)%(\\)=", " rax=\\2\n rax+=rax\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " \\%(\\)=", " rax=\\2\n rax+=rax\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=ax\n",
 " (\\)$(\\)=", " rax=\\2\n rcx=&\\1\n rcx=(rcx)\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\$(\\)=", " rax=\\2\n rcx=&\\1\n rcx+=rax\n rax=rdi\n (rcx)=al\n",
 " \\#++", " rax=&\\1\n rcx=(rax)\n rcx++\n (rax)=rcx\n",
 " \\#--", " rax=&\\1\n rcx=(rax)\n rcx--\n (rax)=rcx\n",
 " \\!++", " rax=&\\1\n ecx=(rax)\n rcx++\n (rax)=ecx\n",
 " \\!--", " rax=&\\1\n ecx=(rax)\n rcx--\n (rax)=ecx\n",
 " \\%++", " rax=&\\1\n cx=(rax)\n rcx++\n (rax)=cx\n",
 " \\%--", " rax=&\\1\n cx=(rax)\n rcx--\n (rax)=cx\n",
 " \\$++", " rax=&\\1\n cl=(rax)\n rcx++\n (rax)=cl\n",
 " \\$--", " rax=&\\1\n cl=(rax)\n rcx--\n (rax)=cl\n",
 "", " (\\)#,\n rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n rdi=(rax)\n",
 " (\\)#=", " rax=&\\1\n rax=(rax)\n (rax)=rdi\n",
 " \\#,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rdi=(rax)\n",
 " \\#=", " rax=&\\1\n (rax)=rdi\n",
 " (\\)!,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n rcx^=rcx\n ecx=(rax)\n rdi=rcx\n",
 " (\\)!=", " rax=&\\1\n rax=(rax)\n rcx=rdi\n (rax)=ecx\n",
 " \\!,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rcx^=rcx\n ecx=(rax)\n rdi=rcx\n",
 " \\!=", " rax=&\\1\n rcx=rdi\n (rax)=ecx\n",
 " (\\)%,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n rcx^=rcx\n cx=(rax)\n rdi=rcx\n",
 " (\\)%=", " rax=&\\1\n rax=(rax)\n rcx=rdi\n (rax)=cx\n",
 " \\%,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rcx^=rcx\n cx=(rax)\n rdi=rcx\n",
 " \\%=", " rax=&\\1\n rcx=rdi\n (rax)=cx\n",
 " (\\)$,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rax=(rax)\n rcx^=rcx\n cl=(rax)\n rdi=rcx\n",
 " (\\)$=", " rax=&\\1\n rax=(rax)\n rcx=rdi\n (rax)=cl\n",
 " \\$,", " rdx=rsi\n rsi=rdi\n rax=&\\1\n rcx^=rcx\n cl=(rax)\n rdi=rcx\n",
 " \\$=", " rax=&\\1\n rcx=rdi\n (rax)=cl\n",
 " \\,", " rdx=rsi\n rsi=rdi\n rdi=\\1\n",
 " data\\", " long \\1\n",
 " \\", " call \\1\n",
NULL
};
