#!/bin/sh

object="a.out"
if test $# -lt 1
then
  echo "./compile source-file [excectable-file]"
  exit 0
fi

if test $# -gt 1
then
 object=$2
fi
./orc stdio.rh $1
java -jar asm_arm.jar asm.s $object
rm asm.s
rm __str
rm __var
rm __tmp1
rm __tmp2
